const express = require("express")
const app = express()
require("dotenv").config()
require("../../database/connection")
app.use(express.json())
app.use(express.urlencoded({extended:true}))
const userRoutes = require("../../routes/user.routes")
app.use("/api/user",userRoutes) 
const postRoutes = require("../../routes/post.routes")
app.use("/api/post",postRoutes)
app.get("*", (req,res)=> res.send( {error:"invalid url"} ) )
module.exports=app